// <auto-generated />
using System;
using Barayand.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Barayand.DAL.Migrations
{
    [DbContext(typeof(BarayandContext))]
    [Migration("20201202091334_AddDeleteFlagToEnergyUsageGiftWrappTable")]
    partial class AddDeleteFlagToEnergyUsageGiftWrappTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Barayand.Models.Entity.AttrAnswerModel", b =>
                {
                    b.Property<int>("X_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("X_Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X_CatAttrId")
                        .HasColumnType("int");

                    b.Property<bool>("X_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("X_Sort")
                        .HasColumnType("int");

                    b.Property<bool>("X_Status")
                        .HasColumnType("bit");

                    b.HasKey("X_Id");

                    b.ToTable("AttributeAnswer");
                });

            modelBuilder.Entity("Barayand.Models.Entity.AttributeModel", b =>
                {
                    b.Property<int>("A_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("A_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("A_SortField")
                        .HasColumnType("int");

                    b.Property<bool>("A_Status")
                        .HasColumnType("bit");

                    b.Property<string>("A_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("A_Type")
                        .HasColumnType("int");

                    b.Property<bool>("A_UseInSearch")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("A_Id");

                    b.ToTable("Attribute");
                });

            modelBuilder.Entity("Barayand.Models.Entity.AuthenticationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllowdUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authentication");
                });

            modelBuilder.Entity("Barayand.Models.Entity.BrandModel", b =>
                {
                    b.Property<int>("B_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("B_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("B_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("B_Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B_Seo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("B_ShowInIndex")
                        .HasColumnType("bit");

                    b.Property<string>("B_SiteLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("B_SortField")
                        .HasColumnType("int");

                    b.Property<bool>("B_Status")
                        .HasColumnType("bit");

                    b.Property<string>("B_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("B_Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Barayand.Models.Entity.CatAttrRelationModel", b =>
                {
                    b.Property<int>("X_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("X_AttrId")
                        .HasColumnType("int");

                    b.Property<int>("X_CatId")
                        .HasColumnType("int");

                    b.Property<bool>("X_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("X_Status")
                        .HasColumnType("bit");

                    b.HasKey("X_Id");

                    b.ToTable("CategoryAttribute");
                });

            modelBuilder.Entity("Barayand.Models.Entity.ColorModel", b =>
                {
                    b.Property<int>("C_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("C_HexColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("C_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("C_Status")
                        .HasColumnType("bit");

                    b.Property<string>("C_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("C_Id");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("Barayand.Models.Entity.CommentModel", b =>
                {
                    b.Property<int>("C_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("C_Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("C_EntityId")
                        .HasColumnType("int");

                    b.Property<int>("C_ParentId")
                        .HasColumnType("int");

                    b.Property<int>("C_Rate")
                        .HasColumnType("int");

                    b.Property<int>("C_Status")
                        .HasColumnType("int");

                    b.Property<int>("C_Type")
                        .HasColumnType("int");

                    b.Property<string>("C_UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("C_UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("C_Id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Barayand.Models.Entity.CopponModel", b =>
                {
                    b.Property<int>("CP_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CP_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CP_Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CP_EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CP_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CP_StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CP_Status")
                        .HasColumnType("bit");

                    b.Property<string>("CP_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CP_Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("CP_Id");

                    b.ToTable("Coppon");
                });

            modelBuilder.Entity("Barayand.Models.Entity.DepartmentModel", b =>
                {
                    b.Property<int>("D_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("D_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("D_SortField")
                        .HasColumnType("int");

                    b.Property<bool>("D_Status")
                        .HasColumnType("bit");

                    b.Property<string>("D_Tel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("D_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("D_Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Barayand.Models.Entity.DynamicPagesContent", b =>
                {
                    b.Property<int>("D_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PageOtherSetting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageSeo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("D_Id");

                    b.ToTable("DynamicPagesContent");
                });

            modelBuilder.Entity("Barayand.Models.Entity.EnergyUsageModel", b =>
                {
                    b.Property<int>("E_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("E_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("E_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("E_Sort")
                        .HasColumnType("int");

                    b.Property<bool>("E_Status")
                        .HasColumnType("bit");

                    b.Property<string>("E_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("E_Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("E_Id");

                    b.ToTable("EnergyUsage");
                });

            modelBuilder.Entity("Barayand.Models.Entity.FavoriteModel", b =>
                {
                    b.Property<int>("F_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("F_EntityId")
                        .HasColumnType("int");

                    b.Property<int>("F_EntityType")
                        .HasColumnType("int");

                    b.Property<int>("F_UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("F_Id");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Barayand.Models.Entity.FormulaModel", b =>
                {
                    b.Property<int>("F_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("F_CatId")
                        .HasColumnType("int");

                    b.Property<string>("F_Formula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("F_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("F_Status")
                        .HasColumnType("bit");

                    b.Property<string>("F_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("F_Id");

                    b.ToTable("Formula");
                });

            modelBuilder.Entity("Barayand.Models.Entity.GalleryCategoryModel", b =>
                {
                    b.Property<int>("GC_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("GC_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GC_Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GC_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("GC_Seo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GC_SortField")
                        .HasColumnType("int");

                    b.Property<bool>("GC_Status")
                        .HasColumnType("bit");

                    b.Property<string>("GC_Titles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GC_Type")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("GC_Id");

                    b.ToTable("GalleryCategory");
                });

            modelBuilder.Entity("Barayand.Models.Entity.ImageGalleryModel", b =>
                {
                    b.Property<int>("IG_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("IG_CatId")
                        .HasColumnType("int");

                    b.Property<string>("IG_ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("IG_SortField")
                        .HasColumnType("int");

                    b.Property<bool>("IG_Status")
                        .HasColumnType("bit");

                    b.Property<string>("IG_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("IG_Id");

                    b.ToTable("ImageGallery");
                });

            modelBuilder.Entity("Barayand.Models.Entity.IndexBoxInfoModel", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("I_Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("I_SecId")
                        .HasColumnType("int");

                    b.Property<int>("I_Sort")
                        .HasColumnType("int");

                    b.Property<string>("I_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("I_Id");

                    b.ToTable("IndexSectionsInfo");
                });

            modelBuilder.Entity("Barayand.Models.Entity.IndexBoxProductRelModel", b =>
                {
                    b.Property<int>("I_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("I_Pid")
                        .HasColumnType("int");

                    b.Property<int>("I_SecId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("I_Id");

                    b.ToTable("IndexSections");
                });

            modelBuilder.Entity("Barayand.Models.Entity.InvoiceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("I_CopponDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("I_CopponId")
                        .HasColumnType("int");

                    b.Property<string>("I_DeliveryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("I_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("I_PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("I_PaymentInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("I_PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("I_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("I_RecipientInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("I_RequestedPOS")
                        .HasColumnType("bit");

                    b.Property<decimal>("I_ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("I_ShippingMethod")
                        .HasColumnType("int");

                    b.Property<int>("I_Status")
                        .HasColumnType("int");

                    b.Property<decimal>("I_TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("I_TotalProductAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("I_UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("Barayand.Models.Entity.ManufacturContryModel", b =>
                {
                    b.Property<int>("M_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("M_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("M_Sort")
                        .HasColumnType("int");

                    b.Property<bool>("M_Status")
                        .HasColumnType("bit");

                    b.Property<string>("M_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("M_Id");

                    b.ToTable("ManufacturingCuntry");
                });

            modelBuilder.Entity("Barayand.Models.Entity.NewsletterModel", b =>
                {
                    b.Property<int>("NL_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("NL_Entity")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("NL_Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("NL_Id");

                    b.ToTable("NewsLetter");
                });

            modelBuilder.Entity("Barayand.Models.Entity.NoticesCategoryModel", b =>
                {
                    b.Property<int>("NC_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NC_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NC_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NC_Seo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NC_SeoUrl")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<int>("NC_SortField")
                        .HasColumnType("int");

                    b.Property<bool>("NC_Status")
                        .HasColumnType("bit");

                    b.Property<string>("NC_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("NC_Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("NC_Id");

                    b.ToTable("NoticesCategory");
                });

            modelBuilder.Entity("Barayand.Models.Entity.NoticesModel", b =>
                {
                    b.Property<int>("N_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N_Attachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("N_CId")
                        .HasColumnType("int");

                    b.Property<string>("N_Content")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<DateTime>("N_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("N_Image")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<bool>("N_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("N_Media")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<int>("N_MediaType")
                        .HasColumnType("int");

                    b.Property<string>("N_Seo")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("N_ShamsiDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("N_Sort")
                        .HasColumnType("int");

                    b.Property<bool>("N_Status")
                        .HasColumnType("bit");

                    b.Property<string>("N_Summary")
                        .HasColumnType("nvarchar(2500)")
                        .HasMaxLength(2500);

                    b.Property<string>("N_Sup")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("N_Title")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("N_Type")
                        .HasColumnType("int");

                    b.Property<string>("N_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("N_Id");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("Barayand.Models.Entity.OfflinRequestModel", b =>
                {
                    b.Property<int>("O_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("O_DeliverDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("O_Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("O_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("O_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("O_Status")
                        .HasColumnType("int");

                    b.Property<string>("O_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("O_User")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("O_Id");

                    b.ToTable("OfflineRequest");
                });

            modelBuilder.Entity("Barayand.Models.Entity.OptionsModel", b =>
                {
                    b.Property<int>("O_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("O_Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("O_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("O_Id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Barayand.Models.Entity.OrderModel", b =>
                {
                    b.Property<int>("O_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("O_Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("O_DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("O_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("O_ProductId")
                        .HasColumnType("int");

                    b.Property<int>("O_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("O_ReciptId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("O_Version")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("O_Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Barayand.Models.Entity.PermissionModel", b =>
                {
                    b.Property<int>("Perm_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Perm_Uid")
                        .HasColumnType("int");

                    b.Property<int>("Perm_Urlid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Perm_Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Barayand.Models.Entity.ProductAttributeModel", b =>
                {
                    b.Property<int>("X_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("X_AId")
                        .HasColumnType("int");

                    b.Property<int>("X_AnswerId")
                        .HasColumnType("int");

                    b.Property<string>("X_AnswerTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X_EntityType")
                        .HasColumnType("int");

                    b.Property<int>("X_PId")
                        .HasColumnType("int");

                    b.HasKey("X_Id");

                    b.ToTable("ProductAttributeAnswer");
                });

            modelBuilder.Entity("Barayand.Models.Entity.ProductCategoryModel", b =>
                {
                    b.Property<int>("PC_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PC_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PC_ImgTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PC_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PC_Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PC_OrderField")
                        .HasColumnType("int");

                    b.Property<int>("PC_ParentId")
                        .HasColumnType("int");

                    b.Property<string>("PC_PrefixCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PC_Seo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PC_Status")
                        .HasColumnType("bit");

                    b.Property<string>("PC_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("PC_Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("PC_Id");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("Barayand.Models.Entity.ProductLabelModel", b =>
                {
                    b.Property<int>("L_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("L_DisplayOnProduct")
                        .HasColumnType("bit");

                    b.Property<string>("L_HexCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("L_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("L_Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("L_Seo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("L_Status")
                        .HasColumnType("bit");

                    b.Property<string>("L_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("L_Id");

                    b.ToTable("ProductLabel");
                });

            modelBuilder.Entity("Barayand.Models.Entity.ProductLabelRelationModel", b =>
                {
                    b.Property<int>("X_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("X_LabelId")
                        .HasColumnType("int");

                    b.Property<int>("X_Pid")
                        .HasColumnType("int");

                    b.HasKey("X_Id");

                    b.ToTable("ProductLabelRelation");
                });

            modelBuilder.Entity("Barayand.Models.Entity.ProductModel", b =>
                {
                    b.Property<int>("P_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Audio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P_Author")
                        .HasColumnType("int");

                    b.Property<int>("P_AvailableCount")
                        .HasColumnType("int");

                    b.Property<int>("P_BinPrice")
                        .HasColumnType("int");

                    b.Property<int>("P_BrandId")
                        .HasColumnType("int");

                    b.Property<string>("P_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Description")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<string>("P_DetailsSubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_DetailsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("P_Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("P_DiscountPeriodTime")
                        .HasColumnType("int");

                    b.Property<int>("P_DiscountType")
                        .HasColumnType("int");

                    b.Property<string>("P_DownloadAbleAudio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_DownloadLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P_EndLevelCatId")
                        .HasColumnType("int");

                    b.Property<decimal>("P_ExternalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("P_GiftBin")
                        .HasColumnType("int");

                    b.Property<string>("P_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_ImgGallery")
                        .HasColumnType("nvarchar(2500)")
                        .HasMaxLength(2500);

                    b.Property<bool>("P_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("P_Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_ListTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P_MainCatId")
                        .HasColumnType("int");

                    b.Property<decimal>("P_PageCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P_PeriodDiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("P_PeriodDiscountPriceType")
                        .HasColumnType("int");

                    b.Property<int>("P_PeriodPrintableFomrulaId")
                        .HasColumnType("int");

                    b.Property<decimal>("P_PeriodPrintablePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("P_PeriodPrintablePriceType")
                        .HasColumnType("int");

                    b.Property<decimal>("P_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("P_PriceFormulaId")
                        .HasColumnType("int");

                    b.Property<int>("P_PriceType")
                        .HasColumnType("int");

                    b.Property<int>("P_PrintAbleVerFormulaId")
                        .HasColumnType("int");

                    b.Property<decimal>("P_PrintAbleVerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("P_PrintAbleVerPriceType")
                        .HasColumnType("int");

                    b.Property<bool>("P_PrintAbleVersion")
                        .HasColumnType("bit");

                    b.Property<int>("P_PriodDiscountFormulaId")
                        .HasColumnType("int");

                    b.Property<string>("P_PublishDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P_SaleCount")
                        .HasColumnType("int");

                    b.Property<string>("P_Seo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("P_Status")
                        .HasColumnType("bit");

                    b.Property<string>("P_TechnicalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("P_Type")
                        .HasColumnType("int");

                    b.Property<string>("P_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P_Video")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<decimal>("P_Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("P_Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Barayand.Models.Entity.Province", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("amar_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("Barayand.Models.Entity.PublicFormsModel", b =>
                {
                    b.Property<int>("F_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_Msg")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<int>("F_MsgSubTopic")
                        .HasColumnType("int");

                    b.Property<int>("F_MsgTopic")
                        .HasColumnType("int");

                    b.Property<int>("F_MsgType")
                        .HasColumnType("int");

                    b.Property<string>("F_Response")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<bool>("F_Status")
                        .HasColumnType("bit");

                    b.Property<int>("F_Type")
                        .HasColumnType("int");

                    b.Property<string>("F_User")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("F_UserEmail")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("F_UserPhone")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("F_Id");

                    b.ToTable("PublicForms");
                });

            modelBuilder.Entity("Barayand.Models.Entity.RateModel", b =>
                {
                    b.Property<int>("R_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("R_EntityId")
                        .HasColumnType("int");

                    b.Property<string>("R_Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("R_Rate")
                        .HasColumnType("int");

                    b.Property<int>("R_Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("R_Id");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("Barayand.Models.Entity.RelatedProductModel", b =>
                {
                    b.Property<int>("PR_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("PR_PId")
                        .HasColumnType("int");

                    b.Property<int>("PR_RId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("PR_Id");

                    b.ToTable("RelatedProduct");
                });

            modelBuilder.Entity("Barayand.Models.Entity.ServiceModel", b =>
                {
                    b.Property<int>("S_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("S_Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_ImageGallery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_Seo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("S_Sort")
                        .HasColumnType("int");

                    b.Property<bool>("S_Status")
                        .HasColumnType("bit");

                    b.Property<string>("S_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("S_Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("S_Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Barayand.Models.Entity.SliderModel", b =>
                {
                    b.Property<int>("S_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_AltTag")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("S_DesktopFileLink")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("S_Link")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("S_MobileFileLink")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("S_OrderField")
                        .HasColumnType("int");

                    b.Property<bool>("S_ShowAnimation")
                        .HasColumnType("bit");

                    b.Property<bool>("S_Status")
                        .HasColumnType("bit");

                    b.Property<string>("S_Titles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_TooltipTitle")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("S_Id");

                    b.ToTable("Slider");
                });

            modelBuilder.Entity("Barayand.Models.Entity.SocialMediaTitlesModel", b =>
                {
                    b.Property<int>("SM_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("SM_Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SM_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("SM_Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("SM_Id");

                    b.ToTable("SocialMediaTitles");
                });

            modelBuilder.Entity("Barayand.Models.Entity.States", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Province")
                        .HasColumnType("int");

                    b.Property<string>("amar_code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Barayand.Models.Entity.StoreModel", b =>
                {
                    b.Property<int>("S_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("S_CityId")
                        .HasColumnType("int");

                    b.Property<int>("S_KeeperId")
                        .HasColumnType("int");

                    b.Property<int>("S_ProvinceId")
                        .HasColumnType("int");

                    b.Property<bool>("S_Status")
                        .HasColumnType("bit");

                    b.Property<string>("S_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("S_Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Barayand.Models.Entity.TicketModel", b =>
                {
                    b.Property<int>("T_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("T_Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("T_Cid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("T_ParentId")
                        .HasColumnType("int");

                    b.Property<int>("T_Status")
                        .HasColumnType("int");

                    b.Property<int>("T_Userid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("T_Id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Barayand.Models.Entity.TrainingModel", b =>
                {
                    b.Property<int>("T_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("T_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("T_Cost")
                        .HasColumnType("float");

                    b.Property<string>("T_Description")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<double>("T_Discount")
                        .HasColumnType("float");

                    b.Property<int>("T_DiscountType")
                        .HasColumnType("int");

                    b.Property<int>("T_EndLevelCatId")
                        .HasColumnType("int");

                    b.Property<string>("T_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_ImgGallery")
                        .HasColumnType("nvarchar(2500)")
                        .HasMaxLength(2500);

                    b.Property<bool>("T_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("T_Level")
                        .HasColumnType("int");

                    b.Property<int>("T_MainCatId")
                        .HasColumnType("int");

                    b.Property<int>("T_SaleCount")
                        .HasColumnType("int");

                    b.Property<string>("T_Seo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("T_Status")
                        .HasColumnType("bit");

                    b.Property<string>("T_Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(5000);

                    b.Property<string>("T_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("T_Video")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("T_Id");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Barayand.Models.Entity.TrainingSeasonsModel", b =>
                {
                    b.Property<int>("S_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("S_Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("S_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("S_Sort")
                        .HasColumnType("int");

                    b.Property<int>("S_TId")
                        .HasColumnType("int");

                    b.Property<string>("S_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("S_Id");

                    b.ToTable("TrainingSeasons");
                });

            modelBuilder.Entity("Barayand.Models.Entity.UserModel", b =>
                {
                    b.Property<int>("U_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("U_Avatar")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("U_Coupon")
                        .HasColumnType("int");

                    b.Property<string>("U_Email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("U_Family")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("U_Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("U_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Phone")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("U_Role")
                        .HasColumnType("int");

                    b.Property<int>("U_RoleId")
                        .HasColumnType("int");

                    b.Property<int>("U_Status")
                        .HasColumnType("int");

                    b.Property<string>("U_SuspendReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("U_Wallet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("U_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Barayand.Models.Entity.VideoGalleryModel", b =>
                {
                    b.Property<int>("VG_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("VG_CatId")
                        .HasColumnType("int");

                    b.Property<string>("VG_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VG_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("VG_Keywords")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("VG_Seo")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<int>("VG_SortField")
                        .HasColumnType("int");

                    b.Property<bool>("VG_Status")
                        .HasColumnType("bit");

                    b.Property<string>("VG_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("VG_UrlType")
                        .HasColumnType("int");

                    b.Property<string>("VG_VideoImage")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.Property<string>("VG_VideoUrl")
                        .HasColumnType("nvarchar(4000)")
                        .HasMaxLength(4000);

                    b.HasKey("VG_Id");

                    b.ToTable("VideoGallery");
                });

            modelBuilder.Entity("Barayand.Models.Entity.WalletHistoryModel", b =>
                {
                    b.Property<int>("WH_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("WH_AdderId")
                        .HasColumnType("int");

                    b.Property<decimal>("WH_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WH_CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("WH_PayBankRecip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WH_PayType")
                        .HasColumnType("int");

                    b.Property<string>("WH_SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WH_TransactionType")
                        .HasColumnType("int");

                    b.HasKey("WH_id");

                    b.ToTable("WalletHistory");
                });

            modelBuilder.Entity("Barayand.Models.Entity.WarrantyModel", b =>
                {
                    b.Property<int>("W_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deleted_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<bool>("W_IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("W_Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("W_Seo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("W_SortField")
                        .HasColumnType("int");

                    b.Property<bool>("W_Status")
                        .HasColumnType("bit");

                    b.Property<string>("W_Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("W_Id");

                    b.ToTable("Warranty");
                });
#pragma warning restore 612, 618
        }
    }
}
